# Generated by Django 2.2.5 on 2019-09-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=250)),
                ('type_school', models.CharField(max_length=10)),
                ('patron', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('regon', models.CharField(max_length=14)),
                ('voivodship', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('house_number', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=250, null=True)),
                ('community', models.CharField(max_length=250, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(null=True)),
                ('girls', models.IntegerField(null=True)),
                ('boys', models.IntegerField(null=True)),
                ('year', models.DateField(null=True)),
                ('staff_amount', models.IntegerField()),
                ('sport_ranking', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specjalization', models.CharField(max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='FinalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('avg_rate', models.IntegerField(null=True)),
                ('pass_rate', models.IntegerField(null=True)),
                ('is_extended', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField(null=True)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Statistics')),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(max_length=100)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Statistics')),
            ],
        ),
    ]
