# Generated by Django 2.2.5 on 2019-09-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodship', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=250)),
                ('house_number', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=250)),
                ('community', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=250)),
                ('type_school', models.CharField(max_length=10)),
                ('patron', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('regon', models.CharField(max_length=14)),
                ('location', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('girls', models.IntegerField()),
                ('boys', models.IntegerField()),
                ('school', models.CharField(max_length=14)),
                ('year', models.IntegerField()),
                ('sport_ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='school_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specjalization', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_properties', models.CharField(max_length=10)),
                ('complexity', models.CharField(max_length=255)),
                ('size_class', models.IntegerField()),
                ('publicity', models.CharField(max_length=255)),
                ('students_cathegory', models.CharField(max_length=100)),
                ('specjalization', models.CharField(max_length=255)),
                ('staff_amount', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='final_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('extended', models.BooleanField()),
                ('avg_rate', models.IntegerField()),
                ('pass_rate', models.IntegerField()),
                ('number_of_ppl', models.IntegerField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Statistics')),
            ],
        ),
    ]
