# Generated by Django 2.2.5 on 2019-09-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(max_length=100)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Statistics')),
            ],
        ),
    ]
