# Generated by Django 2.2.2 on 2019-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalexam',
            name='is_extended',
        ),
        migrations.RemoveField(
            model_name='finalexam',
            name='pass_rate',
        ),
        migrations.AddField(
            model_name='finalexam',
            name='data_type',
            field=models.CharField(choices=[('PP', 'Poziom podstawowy'), ('PR', 'Poziom rozszerzony'), ('ZM', 'Zdawalność')], default='PP', max_length=2),
            preserve_default=False,
        ),
    ]
