# Generated by Django 2.2.5 on 2019-09-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='specjalization',
            new_name='specialization',
        ),
    ]
