# Generated by Django 2.1.5 on 2019-09-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190928_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='country',
            new_name='county',
        ),
    ]
