# Generated by Django 2.2.2 on 2019-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190928_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='nip',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='rspo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
