# Generated by Django 2.2.2 on 2019-09-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190927_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('avg_rate', models.IntegerField(null=True)),
                ('pass_rate', models.IntegerField(null=True)),
                ('is_extended', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='final_exam',
            name='statistic',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.AddField(
            model_name='school',
            name='community',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='county',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='house_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='street',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='voivodship',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='staff_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='specjalization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='boys',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='girls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='final_exam',
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.AddField(
            model_name='finalexam',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Statistics'),
        ),
    ]
