# Generated by Django 2.2.2 on 2019-09-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190928_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerspectiveBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_rating', models.IntegerField()),
                ('global_rating', models.IntegerField()),
                ('wsk', models.FloatField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspective_badge', to='schools.Statistics')),
            ],
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
    ]
