# Generated by Django 2.2.2 on 2019-09-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190928_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='street',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='year',
        ),
        migrations.AddField(
            model_name='statistics',
            name='date',
            field=models.CharField(default=2019, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.TextField(default='Łódź', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='patron',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='regon',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type_school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
