# Generated by Django 2.2.2 on 2019-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190928_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='human_ewd_exam_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='human_ewd_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='math_ewd_exam_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='math_ewd_rate',
            field=models.FloatField(null=True),
        ),
    ]
