# Generated by Django 2.2.2 on 2019-09-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20190928_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='date',
            new_name='year',
        ),
    ]
