# Generated by Django 2.2.2 on 2019-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190928_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='sport_ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='staff_amount',
            field=models.IntegerField(null=True),
        ),
    ]
