version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run: cd BrickSchool
      - run: pip3 install -r requirements.txt
      - run: python3 manage.py test

