version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:1337
    volumes:
      - .:/code
    ports:
      - "8000:1337"
    depends_on:
      - migration
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
