# Generated by Django 2.2.5 on 2019-09-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('0', 'Inteligencja logiczno-matematyczna'), ('1', 'Inteligencja lingwistyczna'), ('2', 'Inteligencja muzyczna'), ('3', 'Inteligencja interpersonalna'), ('4', 'Inteligencja intrapersonalna'), ('5', 'Inteligencja fizyczno-kinestetyczna'), ('6', 'Inteligencja przyrodnicza'), ('7', 'Inteligencja wizualno-przestrzenna')], default='0', max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
