# Generated by Django 2.1.5 on 2019-09-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-quiz',)},
        ),
    ]
