# Generated by Django 2.1.5 on 2019-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190928_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Inteligencja logiczno-matematyczna', 'Inteligencja logiczno-matematyczna'), ('Inteligencja lingwistyczna', 'Inteligencja lingwistyczna'), ('Inteligencja muzyczna', 'Inteligencja muzyczna'), ('Inteligencja interpersonalna', 'Inteligencja interpersonalna'), ('Inteligencja intrapersonalna', 'Inteligencja intrapersonalna'), ('Inteligencja fizyczno-kinestetyczna', 'Inteligencja fizyczno-kinestetyczna'), ('Inteligencja przyrodnicza', 'Inteligencja przyrodnicza'), ('Inteligencja wizualno-przestrzenna', 'Inteligencja wizualno-przestrzenna')], default='0', max_length=100),
        ),
    ]
