# Generated by Django 2.1.5 on 2019-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('0', 'Inteligencja logiczno-matematyczna'), ('1', 'Inteligencja lingwistyczna'), ('2', 'Inteligencja muzyczna'), ('3', 'Inteligencja interpersonalna'), ('4', 'Inteligencja intrapersonalna'), ('5', 'Inteligencja fizyczno-kinestetyczna'), ('6', 'Inteligencja przyrodnicza'), ('7', 'Inteligencja wizualno-przestrzenna')], default='0', max_length=100),
        ),
    ]
