# Generated by Django 2.1.5 on 2019-09-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190928_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
    ]
